/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    CheckInput: typeof import('./components/CheckInput.vue')['default']
    RadioGroup: typeof import('./components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./components/SelectInput.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
  }
}
